services:
  web:
    container_name: web-mem-vision
    build:
      context: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./src:/var/www/html
    depends_on:
      - app

  app:
    container_name: app-mem-vision
    build:
      context: ./docker/app/
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html/
      - ./docker/app/www.conf:/etc/php-fpm.d/www.conf
      - ./docker/app/php.ini:/etc/php.ini
