services:
  web:
    container_name: web-mem-vision
    build:
      context: ./docker/nginx/
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
      - db

  app:
    container_name: app-mem-vision
    build:
      context: ./docker/app/
    ports:
      - "5173:5173"
    volumes:
      - ./src:/var/www/html/
      - ./docker/app/www.conf:/etc/php-fpm.d/www.conf
      - ./docker/app/php.ini:/etc/php.ini

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume:/var/lib/mysql

  db-testing:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - test-mysql-volume:/var/lib/mysql

  # https://qiita.com/layzy_glp/items/bbf4ee5237bae50db9f2
  # ローカルで試せるs3互換
  minio:
    image: "minio/minio:RELEASE.2023-01-02T09-40-09Z.fips"
    volumes:
      - "./minio/data:/data:delegated"
    ports:
      - ${MINIO_API_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
    command: server /data --console-address :9001

  # Bucketの作成（すぐに死ぬ）
  createbuckets:
    image: "minio/mc"
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      echo start_up;
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/${MINIO_BUCKET_NAME};
      exit 0;
      "

volumes:
  mysql-volume:
  test-mysql-volume:
